version: '3.6'
services:
  mysql:
    image: mariadb:10.3.8
    ports:
      - '13306:3306'
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  wordpress:
    image: wordpress:4.9.7-php7.1-apache
    restart: on-failure
    links:
      - mysql:mysql
    ports:
      - '8888:80'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
